# Generated by Django 2.2 on 2019-11-14 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheet',
            name='day',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='hour',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='week',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
